#!/usr/bin/env bash
#installing nginx server on our web

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo rm /var/www/html/index.nginx-debian.html
