#!/usr/bin/env bash
#Installing HAProxy on our loadBalancer

sudo apt-get -y update
sudo apt install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy
#confuguring HAProxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo vi /etc/haproxy/haproxy.cfg
sudo tee -a /etc/haproxy/haproxy.cfg << END
frontend http
    bind *:80
    mode http
    default_backend web-backend
backend web-backend
   balance roundrobin
   server 194121-web-01 54.82.173.73:80 check
   server 194121-web-02	54.237.69.144:80 check
END
sudo systemctl restart haproxy
