#!/usr/bin/env bash
#Installing HAProxy on our loadBalancer

conf="
frontend http
    bind *:80
    mode http
    default_backend web-backend
backend web-backend
   balance roundrobin
   server 194121-web-01 54.82.173.73:80 check
   server 194121-web-02	54.237.69.144:80 check
"
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
printf "%s" "$conf" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
