#!/usr/bin/env bash

# installs the ufw firewall and sets up a few rules on web-01

sudo ufw status
sudo apt-get install -y

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
